### ISSUE TITLE
docs/governance/templates/release.sh is brittle

### ISSUE THREAD

**Issue by Laremere** [GoogleCloudPlatform/open-match#281] opened 2019-04-24 00:38 UTC
It's only run during releases, so I imagine it's easy to break.  Eg, if the list of images changes at all, releases will need to cherrypick a fix to the script.

**Comment by jeremyje** [comment] 2019-04-25 21:45
https://github.com/GoogleCloudPlatform/open-match/issues/250 will address this.

**Comment by jeremyje** [comment] 2019-04-29 13:35
Duplicate of https://github.com/GoogleCloudPlatform/open-match/issues/250

**Closed by jeremyje** 2019-04-29 13:35 UTC
