### ISSUE TITLE
Permission Denied when running release.sh

### ISSUE THREAD

**Issue by sawagh** [GoogleCloudPlatform/open-match#293] opened 2019-04-25 07:51 UTC
In a step to cut the release, I ran the ./docs/governance/templates/release.sh tool to tag the build artifacts with the release version but got access denied. Can you please investigate why I do not have the permissions ? What is the permission model here? Who should get a permission to change tags on open match build artifacts?

**Comment by jeremyje** [comment] 2019-04-29 13:36
Duplicate of https://github.com/GoogleCloudPlatform/open-match/issues/250

The shell script was a stop gap solution for the current replace process. There's definitely issues with it but it's better than manually typing the commands. We'll have to live with it until the Prow migration.

**Closed by jeremyje** 2019-04-29 13:36 UTC
